# Environment for RoPaSci360 board game

In [40]:
from gym import Env
from gym.spaces import Discrete, Box, Dict

from ropasci_game import RoPaSci360

import tensorflow as tf
import numpy as np
import random

In [12]:
INVALID_ACTION_REWARD = -10
VALID_ACTION_REWARD = 10
WIN_REWARD = 100
LOSS_REWARD = -100
EAT_TOKEN = 10

In [63]:
class RoPaSci360(Env):
    def __init__(self,
                player = 'Upper',
                opponent = 'random',
                log = 'True'):
        
        # Constants
        self.max_turns = 360
        self.log = log
                
        #
        # Observation + Action spaces
        # ---------------------------
        #  Observations: RoPaSci board containing 61 hexes, with 9 types of maximum number of tokens for each player.
        #  Actions: (Every board position) * (Every board position)
        #
        # Note: not every action is legal
        #
        self.action_space = Dict({"symbol": Discrete(3), "position": Box(-1, 60, shape = (2,))})
        self.observation_space = Box(-9, 9, (9, 9))
          
        self.player = player
        self.opponent = opponent
        
        self.game = RoPaSci360
        
    def step(self, action):
        assert self.action_space.contains(action), "ACTION ERROR {}".format(action)
        
        symbol = action['symbol']
        position = action['position']
        print(symbol)
        print(position)
                
    def reset(self):
        pass
        
    def render(self):
        pass

IndentationError: unexpected indent (<ipython-input-63-7d83f27569b4>, line 21)

In [22]:
env = RoPaSci360()

In [23]:
env.step

AttributeError: 'RoPaSci360' object has no attribute 'action_space'

In [84]:
action = Dict({"symbol": Discrete(3), "position": Box(0, 61, shape = (2,), dtype = np.uint8)}).sample()
print(-(action['symbol'] + 1), (action['position']))

-2 [42 12]


In [85]:
Box(0, 8, shape=(2,), dtype=np.uint8).sample()

array([8, 0], dtype=uint8)

In [67]:
Box(np.int8(0), np.int8(-1), (9, 9), dtype = np.int8).sample()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)